spring:
  application:
    name: App Spring Boot

  datasource:
    url: jdbc:h2:mem:demo-db # http://localhost:8021/h2-console
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2

  h2:
    console:
      enabled: true

server:
  port: 8021